// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.startupRolloutPrefs.media.peerconnection.mtransport_process", true);
user_pref("app.normandy.startupRolloutPrefs.network.process.enabled", true);
user_pref("app.normandy.user_id", "f1958835-553c-444b-bd64-e082b27844e2");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1620815668);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1620815646);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1620815640);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1620815637);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 107);
user_pref("browser.newtabpage.activity-stream.impressionId", "{2634d159-f241-4f81-b028-89605179a6e7}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.region.update.updated", 1620815641);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1620815669413");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1620817485413");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1620815663199");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1620837263199");
user_pref("browser.search.region", "AL");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1620815639");
user_pref("browser.startup.homepage_override.buildID", "20210415204500");
user_pref("browser.startup.homepage_override.mstone", "88.0");
user_pref("browser.startup.lastColdStartupCheck", 1620815638);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "88.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "d4a804cdd3f24d48857c37f1f48855e9");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210415204500");
user_pref("extensions.lastAppVersion", "88.0");
user_pref("extensions.lastPlatformVersion", "88.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"f40fb308-2421-4f07-8b57-2f056983653d\",\"formautofill@mozilla.org\":\"809a505f-45c5-4490-9f1d-68addf2052e8\",\"pictureinpicture@mozilla.org\":\"b1293c3f-812a-43ce-8ce7-2ad48bb8a42c\",\"screenshots@mozilla.org\":\"355cf3e6-9356-420f-b78e-fc070a373fcf\",\"webcompat-reporter@mozilla.org\":\"fb61f363-d196-4914-9753-3001c31a250e\",\"webcompat@mozilla.org\":\"8386a373-d44d-47eb-9503-2866a0b581cb\",\"default-theme@mozilla.org\":\"b77df7cd-1364-4897-be89-c8331d44427d\",\"google@search.mozilla.org\":\"7e8764f6-9398-4cd6-a6ba-3ed91d551818\",\"amazondotcom@search.mozilla.org\":\"388066f3-fa0e-4f4a-99a0-ed4e3c826d2a\",\"wikipedia@search.mozilla.org\":\"88b37b4b-f0ef-43c1-8a21-089a432ecade\",\"bing@search.mozilla.org\":\"ea7e8610-4384-47ba-b9a3-e34d04d51bf7\",\"ddg@search.mozilla.org\":\"a32ad5eb-052d-40fe-97cf-8aa075c14790\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1620815647);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "81df81a0-c94d-404d-b002-b39b024962a0");
user_pref("security.sandbox.plugin.tempDirSuffix", "aeb73cc9-3f1a-4bac-9224-b01f40ffda15");
user_pref("toolkit.startup.last_success", 1620815637);
user_pref("toolkit.telemetry.cachedClientID", "5d52421e-75a5-49c4-919f-bc844229cb59");
user_pref("toolkit.telemetry.previousBuildID", "20210415204500");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
